name: CI

on:
  pull_request:
    branches: '*'
    types: [opened, edited, reopened, synchronize]
  push:
    branches: [main]

jobs:
  qa:
    name: Quality Assurance

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [16.x]
        os: [ubuntu-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Deps
        run: yarn install

      - name: Run Lint
        run: yarn lint

      - name: Run Tests
        run: yarn test

  release:
    name: Release Package

    runs-on: ubuntu-latest

    if: ${{ github.ref == 'refs/heads/main' }}

    needs: [qa]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Deps
        run: yarn install

      - name: Build
        run: yarn build

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: yarn semantic-release

  publish:
    name: Publish Package

    runs-on: ubuntu-latest

    if: ${{ github.ref == 'refs/heads/main' }}

    needs: [qa, release]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Config Name
        run: git config user.name ${{ secrets.GH_CONFIG_NAME }}

      - name: Config Email
        run: git config user.email ${{ secrets.GH_CONFIG_EMAIL }}

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Deps
        run: yarn install

      - name: Build
        run: yarn build

      - name: Publish Package to Github
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
