name: Publish Public Yarn

on:
  release:
    types: [published]

env:
  targetScope: 'l1b3r'

jobs:
  publish-public:
    name: Publish Public Package to Yarn
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: '12'
          registry-url: 'https://registry.npmjs.org'
          scope: '@${{ env.targetScope }}'

      - name: Config Name
        run: git config user.name ${{ secrets.GH_CONFIG_NAME }}

      - name: Config Email
        run: git config user.email ${{ secrets.GH_CONFIG_EMAIL }}

      - name: Install Deps
        run: yarn install

      - name: Run Lint
        run: yarn lint

      - name: Run Tests
        run: yarn test

      - name: Build Package
        run: yarn build

      - name: Publish Package
        run: yarn publish --access=public --new-version=${{ github.event.release.tag_name }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
