name: Tests

on:
  pull_request:
    branches:
      - master
    types: [opened, edited, reopened, synchronize]

jobs:
  test-pkg:
    name: Test Package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Deps with Node 12
        uses: actions/setup-node@v2
        with:
          node-version: '12'
      - run: yarn install

      - name: Run Tests
      - run: yarn test
