name: Tests

on:
  workflow_dispatch:
  pull_request:
    branches: '*'
    types: [opened, edited, reopened, synchronize]
  push:
    branches: [main]

jobs:
  tests:
    name: Test Package

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [14.x, 16.x]
        os: [ubuntu-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Deps
        run: yarn install

      - name: Run Lint
        run: yarn lint

      - name: Run Tests
        run: yarn test
